GET http://localhost:4000/

###

GET http://localhost:4000/api/workouts/hello

###

GET http://localhost:4000/api/workouts

###

GET http://localhost:4000/api/workouts/1

###

POST http://localhost:4000/api/workouts/

###

DELETE http://localhost:4000/api/workouts/1

###

PATCH http://localhost:4000/api/workouts/1

###