GET http://localhost:4000/api/workouts/hello

###

GET http://localhost:4000/api/workouts

###

GET http://localhost:4000/api/workouts/65f2cb633b5db808378f57f2

###

POST http://localhost:4000/api/workouts/
Content-Type: application/json

{
  "title": "test",
  "reps": "10424230",
  "weight": "1532330"
}

###

DELETE http://localhost:4000/api/workouts/65f2cc96664638b3fa22b8c1

###

PATCH http://localhost:4000/api/workouts/65f2cb5d3b5db808378f57f0
Content-Type: application/json

{
  "title": "situps",
  "reps": "100",
  "weight": "150"
}
###